name: Documentation

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: DOCS
        init-shell: bash
        create-args: >-
          python=3 pip iris numpy sphinx sphinx-rtd-theme --channel conda-forge

    - name: Install gridfill
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Build documentation
      shell: bash -l {0}
      run: |
        set -e
        micromamba activate DOCS
        pushd doc
        make clean html linkcheck
        popd

    - name: Deploy
      if: success() && github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html